name: Docker Image CI

on:
  push:
    paths:
      - ./**
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: |
        echo "$DOCKERHUB_PTA" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t myapp ./Dockerfile
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest

    - name: Deploy with Docker
      if: success()
      run: |
        docker pull ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest
        docker run -d --name myapp -p 8084:80 ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest
