name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and tag Docker image
      run: docker build -t myapp ./community-challenge/Dockerfile

    - name: Tag the Docker image
      run: docker tag myapp:latest ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest

    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest

    - name: Deploy with Docker
      if: success()
      run: |
        docker pull ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest
        docker run -d --name myapp -p 80:80 o${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest
